### ISSUE TITLE
sign in with WC fails

### ISSUE THREAD

**Issue by 2i2i** [2i2i/app_2i2i#711]
this is on test, with an emulator:

E/flutter ( 4824): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_auth/invalid-custom-token] The custom token format is incorrect. Please check the documentation. [ Invalid assertion format. 3 dot separated segments required. ]
E/flutter ( 4824): #0      SetupUserViewModel.signInWithWalletConnect (package:app_2i2i/infrastructure/providers/setup_user_provider/setup_user_view_model.dart:323)
E/flutter ( 4824): <asynchronous suspension>
E/flutter ( 4824): #1      _SignInPageState.onTapSignInWithAlgorand (package:app_2i2i/ui/screens/sign_in/sign_in_page.dart:286)
E/flutter ( 4824): <asynchronous suspension>
E/flutter ( 4824): #2      _SignInPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:app_2i2i/ui/screens/sign_in/sign_in_page.dart:201)

**Comment by 2i2i** [comment]
fixed
